### ISSUE TITLE
AttributeError: flag_values_dict

### ISSUE THREAD

**Issue by oneoyz** [Osier-Yi/SITE#1]
while running the site_param_search.py following error pops up:
Traceback (most recent call last):
  File "site_net_train.py", line 508, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "site_net_train.py", line 501, in main
    run(outdir)
  File "site_net_train.py", line 276, in run
    save_config(outdir+'config.txt')
  File "/SITE-master/simi_ite/util.py", line 60, in save_config
    flagdict = FLAGS.flag_values_dict()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/flags.py", line 44, in __getattr__
    raise AttributeError(name)
AttributeError: flag_values_dict

**Comment by Osier-Yi** [comment]
What's your tensorflow version?

**Comment by Osier-Yi** [comment]
> while running the site_param_search.py following error pops up:
> Traceback (most recent call last):
> File "site_net_train.py", line 508, in 
> tf.app.run()
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
> sys.exit(main(sys.argv[:1] + flags_passthrough))
> File "site_net_train.py", line 501, in main
> run(outdir)
> File "site_net_train.py", line 276, in run
> save_config(outdir+'config.txt')
> File "/SITE-master/simi_ite/util.py", line 60, in save_config
> flagdict = FLAGS.flag_values_dict()
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/flags.py", line 44, in **getattr**
> raise AttributeError(name)
> AttributeError: flag_values_dict

What's your tensorflow version?

**Comment by oneoyz** [comment]
> > while running the site_param_search.py following error pops up:
> > Traceback (most recent call last):
> > File "site_net_train.py", line 508, in
> > tf.app.run()
> > File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
> > sys.exit(main(sys.argv[:1] + flags_passthrough))
> > File "site_net_train.py", line 501, in main
> > run(outdir)
> > File "site_net_train.py", line 276, in run
> > save_config(outdir+'config.txt')
> > File "/SITE-master/simi_ite/util.py", line 60, in save_config
> > flagdict = FLAGS.flag_values_dict()
> > File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/flags.py", line 44, in **getattr**
> > raise AttributeError(name)
> > AttributeError: flag_values_dict
> 
> What's your tensorflow version?

Yes. I updated the tensorflow before and the code worked.
