### ISSUE TITLE
Issue About Python Version

### ISSUE THREAD

**Issue by winstonhong15** [Osier-Yi/SITE#2]
Hi, I just cloned the code from the repository and when I try to run your code I encountered some problems with the print statement. I believe that this issue may be caused by incorrect python versions used on my computer. Can you provide more specific description about the environment you used for this project? Is this project written in Python 2 or Python 3? Thanks.

**Comment by Osier-Yi** [comment]
> Hi, I just cloned the code from the repository and when I try to run your code I encountered some problems with the print statement. I believe that this issue may be caused by incorrect python versions used on my computer. Can you provide more specific description about the environment you used for this project? Is this project written in Python 2 or Python 3? Thanks.

Hi, this project is written in Python 2.7.14. Thanks for your comments and I will add it to the README file
