### ISSUE TITLE
The twins dataset

### ISSUE THREAD

**Issue by dachylong** [Osier-Yi/SITE#3]
Hi, Yi

I am wondering which '40 pre-treatment covariates' you chose for the twins dataset.
I have tried deleting the following features:

'infant_id_0', 'infant_id_1', 'brstate', 'stoccfipb', 'mplbir', 'bord_0', 'bord_1', 'brstate_reg', 'stoccfipb_reg', 'mplbir_reg', 'pldel', 'birattnd'.

to get the 11984 x 40 dimension X matrix, and only get **4821 examples** after removing records with missing values.

I am really confused about the twins dataset.
Could you kindly share your processed Twins dataset?

cheers,
Darcy

**Comment by Osier-Yi** [comment]
> Hi, Yi
> 
> I am wondering which '40 pre-treatment covariates' you chose for the twins dataset.
> I have tried deleting the following features:
> 
> 'infant_id_0', 'infant_id_1', 'brstate', 'stoccfipb', 'mplbir', 'bord_0', 'bord_1', 'brstate_reg', 'stoccfipb_reg', 'mplbir_reg', 'pldel', 'birattnd'.
> 
> to get the 11984 x 40 dimension X matrix, and only get **4821 examples** after removing records with missing values.
> 
> I am really confused about the twins dataset.
> Could you kindly share your processed Twins dataset?
> 
> cheers,
> Darcy

Hi Darcy,

The features I deleted are: 'infant_id_0', 'infant_id_1', 'bord_0', 'bord_1', 'data_year', 'frace', 'fedu6', 'dfageq', 'orfath', 'ormoth', 'mrace', 'cigar6', 'drink5'.

Best,
Liuyi

**Comment by dachylong** [comment]
> > Hi, Yi
> > I am wondering which '40 pre-treatment covariates' you chose for the twins dataset.
> > I have tried deleting the following features:
> > 'infant_id_0', 'infant_id_1', 'brstate', 'stoccfipb', 'mplbir', 'bord_0', 'bord_1', 'brstate_reg', 'stoccfipb_reg', 'mplbir_reg', 'pldel', 'birattnd'.
> > to get the 11984 x 40 dimension X matrix, and only get **4821 examples** after removing records with missing values.
> > I am really confused about the twins dataset.
> > Could you kindly share your processed Twins dataset?
> > cheers,
> > Darcy
> 
> Hi Darcy,
> 
> The features I deleted are: 'infant_id_0', 'infant_id_1', 'bord_0', 'bord_1', 'data_year', 'frace', 'fedu6', 'dfageq', 'orfath', 'ormoth', 'mrace', 'cigar6', 'drink5'.
> 
> Best,
> Liuyi


Hi Liuyi,

Thank you for your reply.

Did you use the data from this link? https://github.com/AMLab-Amsterdam/CEVAE/blob/master/datasets/TWINS/covar_desc.txt

There are totally 52 covariates in the original data. But you deleted 13 covariates as indicated above, then there will be only 52-13=39 left, not 40 covariates. Preprocessing of the Twins dataset really confused me since people are using it by different preprocessing strategies. If you can share your pre-processed data, that will be very helpful.

BTW, do you mean 'feduc6' instead of 'fedu6'?

cheers,
Darcy

**Comment by Osier-Yi** [comment]
> > > Hi, Yi
> > > I am wondering which '40 pre-treatment covariates' you chose for the twins dataset.
> > > I have tried deleting the following features:
> > > 'infant_id_0', 'infant_id_1', 'brstate', 'stoccfipb', 'mplbir', 'bord_0', 'bord_1', 'brstate_reg', 'stoccfipb_reg', 'mplbir_reg', 'pldel', 'birattnd'.
> > > to get the 11984 x 40 dimension X matrix, and only get **4821 examples** after removing records with missing values.
> > > I am really confused about the twins dataset.
> > > Could you kindly share your processed Twins dataset?
> > > cheers,
> > > Darcy
> > 
> > 
> > Hi Darcy,
> > The features I deleted are: 'infant_id_0', 'infant_id_1', 'bord_0', 'bord_1', 'data_year', 'frace', 'fedu6', 'dfageq', 'orfath', 'ormoth', 'mrace', 'cigar6', 'drink5'.
> > Best,
> > Liuyi
> 
> Hi Liuyi,
> 
> Thank you for your reply.
> 
> Did you use the data from this link? https://github.com/AMLab-Amsterdam/CEVAE/blob/master/datasets/TWINS/covar_desc.txt
> 
> There are totally 52 covariates in the original data. But you deleted 13 covariates as indicated above, then there will be only 52-13=39 left, not 40 covariates. Preprocessing of the Twins dataset really confused me since people are using it by different preprocessing strategies. If you can share your pre-processed data, that will be very helpful.
> 
> BTW, do you mean 'feduc6' instead of 'fedu6'?
> 
> cheers,
> Darcy

Hi Darcy,

Sorry for the mistake T.T 
The features that I actually deleted are 'infant_id_0', 'infant_id_1', 'bord_0', 'bord_1', 'data_year', 'frace', 'dfageq', 'orfath', 'ormoth', 'mrace', 'cigar6', 'drink5'.

And yes, I use the data downloaded from the link you mentioned. This is [my pre-processed twins datasets](https://www.dropbox.com/sh/90d1gbr06sj0odi/AABwTtVFrozcoClxSp2YvjfEa?dl=0).

Thank you!
Best,
Liuyi

**Comment by sungyubkim** [comment]
It seems your last reply for pre-processed twins dataset has shifted file names. 

twins_1-10.train.npz has only 541 instances which is approximately 10% of total data and

twins_1-10.test.npz has 4868 instances which is approximately 90% of total data.

Regards,
SungYub Kim

**Comment by Osier-Yi** [comment]
> It seems your last reply for pre-processed twins dataset has shifted file names.
> 
> twins_1-10.train.npz has only 541 instances which is approximately 10% of total data and
> 
> twins_1-10.test.npz has 4868 instances which is approximately 90% of total data.
> 
> Regards,
> SungYub Kim

My apologies for my mistake. The name issue should be corrected now. Thank you for pointing out this!

Best,
Liuyi

**Comment by SongXuchun** [comment]
> 
Hi Darcy,

I have tried deleting the following features Just like you did:

'infant_id_0', 'infant_id_1', 'brstate', 'stoccfipb', 'mplbir', 'bord_0', 'bord_1', 'brstate_reg', 'stoccfipb_reg', 'mplbir_reg', 'pldel', 'birattnd'.
 
However, the final sample size I got was 4821.  Is what I did any different from yours?
Best,
Songxuchun
